### ISSUE TITLE
Wishlist: demo for using 2-D graphics

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#114]
On the old demo page, there was an example for using 2-D images and animations in the scene.  I understood that it should no longer be done in the way that the demo there did it.  However, it is unclear to me what the new method is.  A demo showing this would be best, but that is quite a bit of work, I imagine.  I would also be happy with a short explanation of how to do it.

**Comment by Aeva** [comment]
I put together a 2D rendering demo, which you can find here.  http://mgrl.midnightsisters.org/demos/flat_rendering/

There seems to be a bug in m.grl pertaining to z-sorting which I am attempting to figure what is causing it exactly at the moment.  I'll post the demo to the tutorials section of the forums as well, so as to start populating content.
