### ISSUE TITLE
Image files are loaded multiple times

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#124]
When png files that are part of a gani animation are preloaded, they are still fetched another time when they are needed for rendering the gani.  AFAIK m.grl has a "resource file cache" for this purpose, and it should be used to avoid this second load.

Of course, not preloading them also saves the bandwidth, but it is useful to preload the images for performance reasons.

**Comment by Aeva** [comment]
I can verify that this is happening with the "jta debug" demo.  However, redundant loads do end up pulling from the browser cache, so extra loads don't cost bandwidth, at least on firefox.

Still, this feels like a regression, and is probably related to issue #123.
