### ISSUE TITLE
Keyboard does not work on non-dvorak keyboards

### ISSUE THREAD

**Issue by jhdulaney** [Aeva/m.grl#177]
Well, technically, it does, but keybindings that are expecting to be on, say, qwerty, wind up not working on qwerty keyboards due to this line in mgrl.js:

return please.keys.normalize_dvorak(key);

(line 2113)

**Comment by jhdulaney** [comment]
I note that simply doing return key; resolves the issue.

**Comment by jhdulaney** [comment]
I'm wondering if the thing to do wouldn't be to just use scan codes and then have a lookup table that can be internationalized.

**Comment by jhdulaney** [comment]
Add it to the existing lookup table?

**Comment by Aeva** [comment]
Well, there is a lookup table, but it should only be used when "#dvorak" was added to the url - so the default behavior should be qwerty.  I will look into it.
