### ISSUE TITLE
converting from quaternions to euler angles

### ISSUE THREAD

**Issue by Aeva** [Aeva/m.grl#210]
When a GraphNode's rotation is set with the .rotation property, the .quaternion property gives the equivalent rotation.  Ideally, the reverse should be true as well, but instead, .rotation [will raise an error instead](https://github.com/Aeva/m.grl/blob/4009ce50e7d50307dd5f9d47c5e05d045f672cd8/src/m.graph.js#L362) if you try to read from it when the quat is the primary rotation property.

**Comment by wijnen** [comment]
Having thought a bit about this, I conclude that Euler angles are horrible.  Are you sure you want to use them?  If you instead use axis+angle, the conversion between that and quaternions is simple, and it is also more intuitive what it means.  For Euler angles, IMO it's only intuitive if two of the angles are 0; those cases are trivial to convert to axis+angle.

**Comment by Aeva** [comment]
I find them to be useful, or at least rotate_z to be useful.  I see where you're coming from though.  My rationalization at the moment is basically "well, blender does it".

Basically, everything is a quaternion as far as generating the world matrix is concerned - euler angles are converted automatically via a property driver.

**Comment by wijnen** [comment]
Yes, rotate_* are useful indeed, but if the unit axes get a name, they should be about as easy to make with axis+angle.  Anyway, I have a method for the conversion (which isn't unique):

Rotate (1,0,0) using the quaternion; call the result (x,y,z).
rotate_x for this point did nothing, rotate_y lifts it in z, but doesn't change the angle in the xy projection, and rotate_z does change that angle.  This means that rotate_y can be found from the final z coordinate using asin(z), and rotate_z from x and y using atan2(y,x).

rotate_x is harder:
Transform another point, (1,1,0) using the quaternion and subtract (x,y,z) from it; call the result p.  Transform (1,1,0) with the computed rotate_y and rotate_z and subtract (x,y,z) from that as well; call it e1.  Take the outer product of (x,y,z) and e1 and call it e2.  Then find the projections of p on e1 and e2 by taking the inner product of p with each of these vectors.  Call them p1 and p2.  Use atan2(p2,p1) to determine the angle of p in the (e1,e2)-plane.  That angle is rotate_x.

This is completely untested, and there may be some errors in the method, but in principle something like it should work.

**Comment by wijnen** [comment]
Here's the code; I tested it a bit with angles between -180 and 180 for x an z, between -90 and 90 for y (outside that range, angles within that range are returned that have the same effect as the requested rotation).

```
    var as_euler = function () {
        var xyz = vec3.fromValues(1, 0, 0);
        vec3.transformQuat(xyz, xyz, this.quaternion);
        var rotation_y = -Math.asin(xyz[2]);
        var rotation_z = Math.atan2(xyz[1], xyz[0]);
        var p = vec3.fromValues(1, 1, 0);
        vec3.transformQuat(p, p, this.quaternion);
        vec3.subtract(p, p, xyz);
        var e1 = vec3.fromValues(1, 1, 0);
        vec3.rotateY(e1, e1, vec3.create(), rotation_y);
        vec3.rotateZ(e1, e1, vec3.create(), rotation_z);
        vec3.subtract(e1, e1, xyz);
        vec3.normalize(e1, e1);
        var e2 = vec3.create();
        vec3.cross(e2, xyz, e1);
        vec3.normalize(e2, e2);
        var p1 = vec3.dot(p, e1);
        var p2 = vec3.dot(p, e2);
        var rotation_x = Math.atan2(p2, p1);
        return [rotation_x, rotation_y, rotation_z];
    }.bind(this);
```
