### ISSUE TITLE
Numbering bug on demo page

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#80]
Not entirely sure if this is the right place to report it; if not, please redirect it.

On the demo page at http://pirateradiotheater.org/files/m.grl/demos/, the numbers of the demos work well until 07, but then 08 and 09 show random characters instead.  Perhaps you're accidentilly using octal numbers at some point due to the leading zeros?

**Comment by Aeva** [comment]
Oh!  That's not the canonical page for the project anymore.  See http://aeva.github.io/m.grl/#demos
The old demo page is "deprecated" - I got tired of the numbering scheme and decided to be funny and give it a "glitchy" name.  The demos will likely be rewritten during the process of documenting m.grl that will happen soon, and the old page will be deleted all together.

**Comment by wijnen** [comment]
Ah, that explains.  But the new page still points to something that looks a lot like the old page with the "Back to Demo Index" links.

**Comment by Aeva** [comment]
yeah, I need to clean it up still.  The old demo index page is fine, provided its on the correct domain :)
