### ISSUE TITLE
Last animation frame referenced incorrectly

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#86]
Line 1172 says `var frame = action.frames.slice(-1);`, but the next line expects frame to be an object, not an array.  So `[0]` should be added to line 1172.

**Comment by Aeva** [comment]
Current master branch seems to already have this change?

**Comment by wijnen** [comment]
I must have wgetted an older version from one of the demo pages originally.  Sorry about that.

**Comment by Aeva** [comment]
^_^ is ok
