### ISSUE TITLE
Exporter produces incorrect position for first frame

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#89]
I have a simple setup: one mesh, one bone, one action which moves the bone to positions (0,0,0), (0, -1, 1), (0, -2, 0) at frames 0, 10, 20 respectively.

When exporting this the jta file instead contains "position": {"y": -2.0, "z": 0.0, "x": 0.0} for the first frame.  The other two frames are correct.

I'm trying to find the problem, but when I run bone.decompose() in the Blender-internal Python commandline, it complains that the matrix isn't 4×4 (and that is correct, it is 3×3).  I don't know why the exporter doesn't suffer from this.

**Comment by wijnen** [comment]
Found it.  In ani_data.py, line 119, the cache is filled with the object of the first frame.  This cache object is adjusted for each next computation and since the object is not copied, this changes the data in the first frame.  Instead, a deep copy is required (for example with {key: changed[key].copy() for key in changed}).

I tested this and it produces proper coordinates in the first frame.

**Comment by wijnen** [comment]
Follow-up: since all the values in the cache are always replaced, never changed, a simple shallow copy is good enough (cache[bone.name] = changed.copy()).

**Comment by Aeva** [comment]
Awesome :) I've applied your fix and it is now in master.
