### ISSUE TITLE
Non-repeating animations render incorrectly

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#90]
When an animation is finished, the last frame is activated again.  The result of this is that the move to the last keyframe is repeated; I don't know if this would be expected (I didn't check if a frame callback is supposed to move to or from a frame), but in any case the result is that the final segment of the move is duplicated.

Disabling the frame callback in lines 178-179 in m.time.js (1172-1173 in mgrl.js) makes it work properly.  I do not know if this breaks anything as a side effect.

**Comment by Aeva** [comment]
I think the lines in question were a throwback from an older version of the frame tracker, and aren't needed anymore.  Excellent work ^_^
