### ISSUE TITLE
Feature Request: Access scene objects by name

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#96]
It would be nice if the objects in a scene were accesible by name after loading the whole scene.  For example:
```
scene = please.access('scene.jta').instance();
cube = scene.parts['cube'];
```
Another interface is fine as well, the feature I would like is to load a file full of objects with a single instance() call, and then be able to access the objects in it individually.  At the moment this is possible by calling instance() for each of them separately, which is cumbersome.

**Comment by Aeva** [comment]
This currently exists such that non-bone elements can be accessed via
```
scene = please.access('scene.jta').instance();
scene.node_lookup['Cube'];
```
Theoretically (not recently tested, so this might not actually work), if you only wanted just a specific item (bone or otherwise) you could just do 
```
scene = please.access('scene.jta').instance('Cube');
```
If you want to reference bones, you can do so like so:
```
scene = please.access('scene.jta').instance();
scene.armature_lookup['SomeBoneName'];
```

**Comment by Aeva** [comment]
Ok, this syntax can be used to instance a specific node, but the result lacks the 'node_lookup' mechanism.
```
scene = please.access('scene.jta').instance('Cube');
```
This probably also won't work for animation machinery.  Inheritance is untested.

**Comment by wijnen** [comment]
I was using the second method, and can confirm that it works.  I didn't even try animations from it, because they are a property of the scene, not the object, so I don't see how they could work.

I just tested the node_lookup and that works fine as well.  I suppose the animation does work then, given that the scene is instanced, but at the moment all my animations are scripted, so I can't easily test jta animations.

I would remove the bug tag, it's only a documentation issue.

**Comment by Aeva** [comment]
It is probably fine as is, though I am wondering if maybe the ability to invoke an object's animation individually would be useful or not.

**Comment by wijnen** [comment]
I don't see how that could work.  If you instance an object without instancing the scene, the context in which the animation should work is not available.

I suppose it would be possible to detect that an animation is using an object, and so it is taken as being a part of that object.  But what about animations that involve multiple objects?

I would define instance(name) as an implementation detail which should not be used from outside the library.  Using node_lookup isn't any harder, and it makes a lot more sense.

**Comment by Aeva** [comment]
node_lookup was an afterthought; both function as a mechanism for picking out a subset of the graph tree from jta files, but the instance part avoids building unnecessary gpu primitives.

I think it would be trivial to add the animation hooks for individual objects, but I the only use case I can think of is kind of silly anyway :P

**Comment by wijnen** [comment]
I'd be worried about stimulating people to do it wrong.  My guess is that if you support animations for single instanced objects, the animation machinery is loaded multiple times if multiple objects from the same scene are instanced, and that sounds like a bad idea to me.  So if you want that, you should instead use node_lookup.  But if single object instancing is available and documented as part of the API, people will do it wrong and use that when they shouldn't.

That's why I think you should document this issue (if it actually exists) if there is a good reason to have it part of the API, or otherwise not make it part of the API.  The implication of the latter would be that you need to create the jta file specifically for the game (as opposed to exporting a huge file full of objects of which you use only a few), but that's a good idea anyway.

If there isn't any cost in terms of resources when instancing multiple single objects with animations from one scene, forget what I wrote here. :-P

**Comment by Aeva** [comment]
My feelings on this is that whatever the instance command returns should have animation machinery on it, but whatever node_lookup returns should not (for the problem redundancy creates, which you described).

Part of the rational is using a JTA file not to represent a scene, but also to be able to represent multiple resources that would usually be loaded together.  This is less useful for animations, and is intended more to allow for a file contain several variations on the same thing (eg, a jta file that contains 3D models of the letters of the alphabet).  The rational for animation machinery is for the sake of being consistent.

**Comment by Aeva** [comment]
closing this ticket because the mechanism for instancing only part of a scene is now described in the reference pages at least http://mgrl.midnightsisters.org/docs/build/html/api_reference/m.jta.html
